### ISSUE TITLE
Command block only responsive to keyboard

### ISSUE THREAD

**Issue by nckre** [sadmann7/shadcn-table#119]
Clicking on the filters opens the command box and it's responsive to keyboard input but I cannot click any of the filters.

![CleanShot 2024-03-14 at 17 19 17](https://github.com/sadmann7/shadcn-table/assets/29370294/06b8df7f-4488-4ef8-a496-19515fc2e086)

**Comment by noxify** [comment]
With the latest `cmdk` version, there is a breaking change in the behavior.

There are some issues & PRs to fix this.

Related:
* https://github.com/shadcn-ui/ui/issues/2944#issuecomment-1985153126 for disabled items fix
* https://github.com/shadcn-ui/ui/issues/2944#issuecomment-1986020090 for error fix
* https://github.com/shadcn-ui/ui/pull/2945

**Comment by sadmann7** [comment]
Thanks for reporting,

Pushed a temporary fix, should be good now.

**Comment by nckre** [comment]
Yep, just tested, it's good now, thanks both for the info and the quick fix!
