### ISSUE TITLE
Filters are not saved in full refresh.

### ISSUE THREAD

**Issue by edeuxk** [sadmann7/shadcn-table#14]
Example click on this link.
https://shadcn-table-alt.vercel.app/?page=1&status=in-progress&priority=medium

We should have status set to "in progress" and priority set to "medium".
Instead of this, everything is reset.

https://github.com/sadmann7/shadcn-table/assets/8247995/479a6829-a6da-47e1-a92f-4391eea2e15c

**Comment by noxify** [comment]
it seems `filterableColumns` is empty after refreshing the page, so the original condition is correct and the problem is somewhere else

**Comment by noxify** [comment]
I was wrong - it's `columnFilters` - it's not filled after refreshing the page.

**Comment by noxify** [comment]
Found a way to solve this issue - PR created.

**Comment by sadmann7** [comment]
Thanks a lot @noxify

**Comment by edeuxk** [comment]
Issue is still here when you have no selected filters, only page=2, it will redirect you to page 1.
Example: https://table.sadmn.com/?page=2
