### ISSUE TITLE
Loading indicator during filter / search / pagination

### ISSUE THREAD

**Issue by tonyxiao** [sadmann7/shadcn-table#15]
Sorely missing at the moment. Would love an example for how to implement it.

**Comment by sadmann7** [comment]
`tsx
export default function TasksTablePage({ searchParams }: TasksTablePageProps) {
  const { page, sort } = searchParamsSchema.parse(searchParams)
  const tasksPromise = getTasks(searchParams)

  return (
    <Shell>
      <React.Suspense
        key={`${page}-${sort}`}
        fallback={
          <DataTableSkeleton columnCount={4} filterableColumnCount={2} />
        }
      >
        {/**
         * The `TasksTableShell` component is used to render the `DataTable` component within it.
         * This is done because the table columns need to be memoized, and the `useDataTable` hook needs to be called in a client component.
         * By encapsulating the `DataTable` component within the `tasktableshell` component, we can ensure that the necessary logic and state management is handled correctly.
         */}
        <TasksTableShell tasksPromise={tasksPromise} />
      </React.Suspense>
    </Shell>
  )
}

`

**Comment by sadmann7** [comment]
```tsx
export default function TasksTablePage({ searchParams }: TasksTablePageProps) {
  const { page, sort } = searchParamsSchema.parse(searchParams)
  const tasksPromise = getTasks(searchParams)

  return (
    <Shell>
      <React.Suspense
        key={`${page}-${sort}`}
        fallback={
          <DataTableSkeleton columnCount={4} filterableColumnCount={2} />
        }
      >
        {/**
         * The `TasksTableShell` component is used to render the `DataTable` component within it.
         * This is done because the table columns need to be memoized, and the `useDataTable` hook needs to be called in a client component.
         * By encapsulating the `DataTable` component within the `tasktableshell` component, we can ensure that the necessary logic and state management is handled correctly.
         */}
        <TasksTableShell tasksPromise={tasksPromise} />
      </React.Suspense>
    </Shell>
  )
}
```

**Comment by tonyxiao** [comment]
Hmm I see. What if you want to follow the stale-while-revalidate pattern and keep showing the data just with a refreshing indicator before the updated data comes back in?

**Comment by sadmann7** [comment]
React suspense will handle that as its triggering the suspense for that unique key.

**Comment by DivMode** [comment]
Is there a way to make it so that only the table rows show the skeleton? With the current solution the whole table including column headers and page numbers becomes a skeleton

**Comment by araggohnxd** [comment]
@DivMode not only that, but if the filter in question is a faceted filter, re-rendering the table causes the filter UI to not display the filtered values correctly

**Comment by adarshaacharya** [comment]
@tonyxiao @DivMode did you found any solution for this

**Comment by adarshaacharya** [comment]
@DivMode even filterable fields become skeleton which is quite annoying
