### ISSUE TITLE
how to use Global filter 

### ISSUE THREAD

**Issue by thearith-dfh** [sadmann7/shadcn-table#162]

**Comment by yasseralsaidi** [comment]
by adding this: 

`
  const [globalFilter, setGlobalFilter] = React.useState(null);
  
    const table = useReactTable({
       ...
    onGlobalFilterChange: setGlobalFilter,
       ...
    state: {
      globalFilter,
    },
  });
`

**Comment by matcastaneda** [comment]
Uou can check the [TanStackTable](https://tanstack.com/table/) documentation, it is very complete, I leave you the link: https://tanstack.com/table/v8/docs/api/features/global-filtering

**Comment by sadmann7** [comment]
Filtering that many columns server side might not be a good approach.

Maybe it should be used on the client side.

You can follow the example, and docs provided above to get started.
