### ISSUE TITLE
sonner vs. shadcn toast?

### ISSUE THREAD

**Issue by tonyxiao** [sadmann7/shadcn-table#17]
shadcn already has a toast component. So why do we use sonner? Seems to be adding an extra dependency

**Comment by sadmann7** [comment]
Because it looks cooler.

You can check out the shadcn sonner component [https://ui.shadcn.com/docs/components/sonner](url).

**Comment by tonyxiao** [comment]
ah cool. Didn't know it's already included in shadcn/ui already. Thanks for the tip
