### ISSUE TITLE
Page size is not working?

### ISSUE THREAD

**Issue by francescreig** [sadmann7/shadcn-table#18]
Hello! First of all great contribution to OSS on how to use shadcn with server side pagination, not an easy task.

I was testing the implementation and it seems that when setting different page size from initial (p.e.: 20) is not working?

Thanks a lot

EDIT: I've been testing a little bit more and I found that if you set it on the URL it works, but when changing on the popover don't. Also I have checked that, for example if you are on the second page and then you change the page size from 20 to 10, it does not reload and instead it goes to the 3rd page.

**Comment by sadmann7** [comment]
Thanks a lot of reporting the issue.

I fixed it.

**Comment by francescreig** [comment]
Thank you to you for this package and the quick response! 👏🏼
