### ISSUE TITLE
what params to have full page display without pagination and scroll

### ISSUE THREAD

**Issue by jpainam** [sadmann7/shadcn-table#188]
Hi. what params in the `useDataTable` to set to have a full page without pagination?

`pageCount: -1` or `pageCount: 1` doesn't work?

**Comment by sadmann7** [comment]
You maybe looking for infinite scrolling with row virtualization.

There is a demo of it in the tanstack-table docs.

**Comment by JuanPedroPontVerges** [comment]
Any implementation of this server-side pagination with infinite scroll instead of pages?
