### ISSUE TITLE
[Bug] useDataTable: Allow schema parameter to override default createdAt sort

### ISSUE THREAD

**Issue by john093e** [sadmann7/shadcn-table#233]
### Describe the bug

Hello @sadmann7,

The useDataTable is currently always adding "createdAt.desc" to the URL, as it is the default sort in the use-data-table schema constant.

This is an issue, as we might need "updatedAt" or another type of time sorting, or even no time sorting at all, like sorting simply by IDs.

It seems to me that we should make the schema a mandatory parameter for the use-data-table, so users can choose whether to default to "createdAt", somthing else or nothing at all (thus using the ID as it is the default in queries.ts).

Kind regards.

### How to reproduce

 - 

### Link to reproduction

-

**Comment by sadmann7** [comment]
Thanks for opening the issue.

Updated the `useDataTable` hook to handle perPage and sort props.

```ts
  const { table } = useDataTable({
    data,
    columns,
    pageCount,
    // optional props
    filterFields,
    enableAdvancedFilter,
    defaultPerPage: 10,
    defaultSort: "createdAt.desc",
  })
```
