### ISSUE TITLE
[bug]: Advanced Filter doesn't appear to work in demo

### ISSUE THREAD

**Issue by ZipBrandon** [sadmann7/shadcn-table#256]
### Describe the bug

No results returned.

### How to reproduce

Turn on advance filtering
Filter by something

### Link to reproduction

https://table.sadmn.com/?page=1&sort=createdAt.desc&per_page=10&operator=and&title=We.contains

### Additional information

Note that the link generated by the advanced filtering case does not initialize the table state appropriately in an advanced state, too.

**Comment by waltershewmake** [comment]
I've noticed that the advanced filter just doesn't seem to work in general unless you're using the "Contains" option. If you switch to any other choice, like "does not contain," "is," etc, it doesn't work at all.

**Comment by nuclei272** [comment]
Not working for me aswell. From what I've seen in `queries.ts`, it's not taking into account those changes with advanced filter.

**Comment by sadmann7** [comment]
updated the advanced filter with a few different filter variant

should work fine now
