### ISSUE TITLE
[feat]: Grouping Support

### ISSUE THREAD

**Issue by izakfilmalter** [sadmann7/shadcn-table#299]
### Feature description

Would love to see grouping support: https://tanstack.com/table/latest/docs/guide/grouping

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by sadmann7** [comment]
you can just group the columns in the column definitions.

here is a demo of [column grouping](https://tanstack.com/table/v8/docs/framework/react/examples/column-groups)
