### ISSUE TITLE
[bug]: Date range isn't persisted across reloads

### ISSUE THREAD

**Issue by dBianchii** [sadmann7/shadcn-table#309]
### Describe the bug

Date range in UI isn't persisted across reloads

![image](https://github.com/sadmann7/shadcn-table/assets/17372417/6071a4ec-0b46-4bdf-a9bf-c65769e00e3d)

### How to reproduce

1. Go to https://table.sadmn.com/?page=1&sort=createdAt.desc&per_page=30&operator=and&from=2024-05-08&to=2024-06-03
2. Notice the date range is not selected in the UI, although the filter is being applied correctly

### Link to reproduction

https://table.sadmn.com/?page=1&sort=createdAt.desc&per_page=30&operator=and&from=2024-05-08&to=2024-06-03

**Comment by sadmann7** [comment]
thanks for reporting it. fixed it in the latest pr
