### ISSUE TITLE
[feat]: Determine per_page on container/viewport on load

### ISSUE THREAD

**Issue by iamgp** [sadmann7/shadcn-table#326]
### Feature description

I'd like to have as many rows in the table as possible to fill the container/viewport on load (i.e. no need on resize). At the moment it is set by a select dropdown.

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by sadmann7** [comment]
wouldn't a virtualized table with infinite scrolling be more usable for your use case.

you can see the implementation [here](https://tanstack.com/table/v8/docs/framework/react/examples/virtualized-infinite-scrolling)
