### ISSUE TITLE
 pageCount: number vs   defaultPerPage?: number;

### ISSUE THREAD

**Issue by jpainam** [sadmann7/shadcn-table#357]
### Describe the bug

I see these two params defined as:

```ts
  /**
   * The number of pages in the table.
   * @type number
   */
  pageCount: number;

  /**
   * The default number of rows per page.
   * @default 10
   * @type number | undefined
   * @example 20
   */
  defaultPerPage?: number;
```

### How to reproduce

What exactly the difference between the two. `pageCount` is required, and then, why defaultPerPage.

### Link to reproduction

N/A

**Comment by sadmann7** [comment]
page count is required by `tanstack-table` for doing server side pagination.

and defaultPerPage is how many items you wanna show per page by default

**Comment by jpainam** [comment]
So `defaultPerPage` is actually the `pageSize` and its value is one from `pageSizeOptions = [10, 20, 30, 40, 50]` and not any number.
I would suggest we typed this variable, to enforce its value.

**Comment by sadmann7** [comment]
its what do you want by default in the page size options,

its default to the first value now.

this can be changed by the defaultPerPage prop
