### ISSUE TITLE
[bug]: Blank page

### ISSUE THREAD

**Issue by john-dw** [sadmann7/shadcn-table#360]
### Describe the bug

https://table.sadmn.com/ -> blank page

### How to reproduce

enter ->

### Link to reproduction

https://table.sadmn.com/

**Comment by sadmann7** [comment]
should be fixed now.

don't know why its showing up every few days.

also just updated to react 15, with react-compiler enabled

**Comment by Hermitauge** [comment]
Page is back with no entries. This was a fantastic work you were developing. It would be great if you give life back into it as it was a great learning experience for us learning from how you were doing it.

I will check the project again soon. Thanks for the great work.

**Comment by sadmann7** [comment]
was some weird build issue.

its fixed now
