### ISSUE TITLE
Page parameter resets back to page 1

### ISSUE THREAD

**Issue by seoulkimchi88** [sadmann7/shadcn-table#38]
Hi, thank you very much for creating this wonderful component.. This is really helpful.

One issue i have though while using it was that the page parameter resets back to `page=1` if I reload the browser while I'm in a different page (ex. `page=3`). 
It also reset back to page=1 if I directly visit a url with parameter (ex. page=2, page=3, etc. ) 

https://github.com/sadmann7/shadcn-table/assets/112804365/6ea03cf5-26c5-4d57-b6f5-e728b9f1e8fd

**Comment by sadmann7** [comment]
Thanks for reporting.

Should be fixed now.
