### ISSUE TITLE
[feat]: draggable column like ant design

### ISSUE THREAD

**Issue by askareija** [sadmann7/shadcn-table#395]
### Feature description

Hi, i love this project! i don't know if this possible but right now as you can see we have option to select which columns to display.

![240606_09h55m05s_screenshot](https://github.com/sadmann7/shadcn-table/assets/21377617/0f530db9-a884-42a4-a507-049abeb1e44e)

An idea emerged what if the column list was added with drag & drop like in the Ant Design table so we can arrange the table columns?

![240606_09h54m38s_screenshot](https://github.com/sadmann7/shadcn-table/assets/21377617/6eaad45e-3b80-4e73-9ff1-8a0295859a25)

### Additional Context

[Ant design table demo](https://preview.pro.ant.design/list/table-list)

### Before submitting

- [x] I've made research efforts and searched the documentation
- [x] I've searched for existing issues and PRs

**Comment by sadmann7** [comment]
don't wanna make the component bloated with all the table modules

can see this repo [data-table-filters](https://github.com/openstatusHQ/data-table-filters) for the implementation
