### ISSUE TITLE
[bug]: No data on demo website

### ISSUE THREAD

**Issue by wowjulian** [sadmann7/shadcn-table#405]
### Describe the bug

No data on demo website, no items in the table

### How to reproduce

1. Go to https://table.sadmn.com/
2. 
![image](https://github.com/sadmann7/shadcn-table/assets/151126027/41e5e261-a45d-4c11-a266-4bee2f711954)

### Link to reproduction

https://table.sadmn.com/

**Comment by sadmann7** [comment]
don't why its keep happening. i changed the db a few weeks ago. maybe something went wrong that time.

should be fixed now.
