### ISSUE TITLE
floating bar doesn't float or stay at bottom-1

### ISSUE THREAD

**Issue by jpainam** [sadmann7/shadcn-table#53]
Hi
I was expecting the floating bar to stay at `bottom-1` position and always be visiblte on the screen. 
Not only it goes all way down when in increase the `pageSize`, but it doesn't stay fix.

<img width="364" alt="Screenshot 2024-02-26 at 12 22 22 PM" src="https://github.com/sadmann7/shadcn-table/assets/1701705/6152c5ad-df01-497c-b963-3e5645615d81">

**Comment by noxify** [comment]
Which `bottom-1` do you mean?
Checked the html from the demo and there is no `bottom-1` specified.

**Comment by jpainam** [comment]
I got it. i was expecting the `floating bar` to really be floating, be `fixed` and positionned at the `bottom`.

I'll just rewrite the `css` in my component.
Thanks.
