### ISSUE TITLE
[feat]: pagination link

### ISSUE THREAD

**Issue by andredewaard** [sadmann7/shadcn-table#615]
### Feature description

via the shadcn pagination component and links instead of buttons

### Additional Context

[pagination component](https://ui.shadcn.com/docs/components/pagination)
[Link integration](https://ui.shadcn.com/docs/components/pagination#nextjs)

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

**Comment by sadmann7** [comment]
i use [nuqs](https://nuqs.47ng.com) for handling query strings

with the next link it will be difficult to do
