### ISSUE TITLE
[bug]: advanced filters not work

### ISSUE THREAD

**Issue by Sylvesterx1** [sadmann7/shadcn-table#629]
### Describe the bug

I see code responsible for advanced filter, but on button click also in  your demo is hidden default fitlers, and not showing advanced filters. 

### How to reproduce

on button click also in  your demo is hidden default fitlers, and not showing advanced filters. 

### Link to reproduction

https://table.sadmn.com/

**Comment by noxify** [comment]
@Sylvesterx1 - If you activate the "advanced filter" you will find a "Filter" button on the right side ( shown after the "Export" Button ).

<img width="673" alt="image" src="https://github.com/user-attachments/assets/91ae24eb-9394-4d1c-aef1-46988cbf85c5">

**Comment by sadmann7** [comment]
updated advanced filter

should work fine now
