### ISSUE TITLE
[bug]: Application error: a server-side exception has occurred (see the server logs for more information).

### ISSUE THREAD

**Issue by Rot4tion** [sadmann7/shadcn-table#635]
### Describe the bug

Application error: a server-side exception has occurred (see the server logs for more information).

### How to reproduce

https://[table.sadmn.com](https://table.sadmn.com/)/

### Link to reproduction

dont have

**Comment by a0m0rajab** [comment]
I think this happened due to package updates

**Comment by sadmann7** [comment]
#638 fixed it

**Comment by a0m0rajab** [comment]
Thanks it's working now
