### ISSUE TITLE
[bug]: selecting date and choosing the "is between" operator crashes application

### ISSUE THREAD

**Issue by abiodunooni** [sadmann7/shadcn-table#647]
### Describe the bug

When filtering by created at and choosing the is between operator, the application crashes

### How to reproduce

1. Enable advanced filters
2. Add a created at filter
3. choose the 'Is between' operator

### Link to reproduction

https://table.sadmn.com/?flags=advancedFilter&filters=[{%22id%22:%22createdAt%22,%22value%22:%22%22,%22type%22:%22date%22,%22operator%22:%22isBetween%22}]

### Additional information

Attached a URL to with the right filters applied

**Comment by sadmann7** [comment]
should be fixed now
