### ISSUE TITLE
All filters are not always being reset

### ISSUE THREAD

**Issue by brentrobbins** [sadmann7/shadcn-table#7]
I noticed in the demo when you select a filter and also use the Title search/filter, once you click on reset; the filter value is not fully reset and still is preset in the URL. Here's a quick screencast top to show you what I am running into. 

https://github.com/sadmann7/shadcn-table-v2/assets/727491/4bf1a095-fb28-4c5a-9379-a69da25c5a52

By the way, thank you so much @kavinvalli & @sadmann7 for creating this. I found it while watching your livecode247 channel on youtube. It has been very helpful and exactly what I have been looking for. 🙏🏻

**Comment by sadmann7** [comment]
Thanks for the issue.

I will look into it

**Comment by CyanFlare** [comment]
Hello,
Any updates on this issue? I'm having the same issue with the filters not fully being reset.

**Comment by iaingymware** [comment]
Any update on this please or is this now a dead repo?

**Comment by dewodt** [comment]
Same here.

**Comment by dewodt** [comment]
I have tried fixing it in pull request #13. Maybe @sadmann7 @kavinvalli can review my pull request. Thank you.

**Comment by sadmann7** [comment]
Thanks a lot @dewodt.

Closing this issue.
